### ISSUE TITLE
Handle different response types from API

### ISSUE THREAD

**Issue by macabu** [macabu/pagoda_bot#1]
The OpenWeatherMap API responds with a string for the member "cod", whenever the response status is not found (404).
The current JSON deserialization implementation uses serde_json, and matches the JSON with a Struct, which cannot be both String and i32 at the same time.

**Comment by wilkmaia** [comment]
I have a few questions:

- Do you have an example of a request that returns something other than `200`?
- Is this a problem that regularly crashes the bot?

**Comment by macabu** [comment]
Fixed description, it is only when the response is `404` (city not found), but inside src/test_weather.rs there is a function `nepravilno_nazvanie` (also I should work on renaming said functions).  
The problem doesn't crash the bot as I have handled it (by creating a dummy JSON response), which I am not satisfied with.
